services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 3001
    ports:
      - "3001:3001"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "80:80"
